# Reproducibility (taking out random out of ramdom)
### In short how neural network learns is :
- start with random numbers -> tensor operations -> update random numbers to make the mbetter representations of data -> again -> again -> again ...
- to reduce the randomness in pytorch and neural networks, use the concept of *random seed*
- *random seed* flavours the radomness
- 

In [1]:
# importing
try:
    import torch
    import numpy
    import matplotlib.pyplot as plt
    print("Done Successfully")
except Exception as e:
    print("Failed to import",e)


Done Successfully


In [4]:
# create two random tensors :
t1=torch.rand([3,3]) # uses random seed which we can checy by torch.initial_seed()
t2=torch.rand([3,3])
print(t1,"\n",t2)

tensor([[0.2043, 0.3829, 0.3905],
        [0.6666, 0.8002, 0.1315],
        [0.5394, 0.1454, 0.1651]]) 
 tensor([[0.9362, 0.8073, 0.2342],
        [0.9628, 0.5880, 0.1038],
        [0.2923, 0.3586, 0.8057]])


In [6]:
# check if any of the values are equal in these two tensors 
print(t1==t2) #none 

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [15]:
# lets create a random seed and use it to do the same 
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED) # set a manual seed 

t3=torch.rand([3,3])

torch.manual_seed(RANDOM_SEED) # set a manual seed again because its lost after each call of torch.rand()
t4=torch.rand([3,3])

print(t3,"\n",t4)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [16]:
# check again if any of the values are equal in these two tensors 
print(t3==t4) # notice the reproducibility


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
