In [24]:
# importing
try:
    import torch
    import numpy
    import matplotlib.pyplot as plt
    print("Done Successfully")
except Exception as e:
    print("Failed to import",e)


Done Successfully


In [6]:
# create a tensor
s1= torch.tensor([7,8])

print(s1)
print(s1+7) # `+` or `torch.add` adds the number to all the elements in the tensor
print(s1-7) # `-` or `torch.sub` substracts the number from all the elements in the tensor
print(s1*2) # `*` or `tensor.mul` multiplies the number to all the elements in the tensor 
print(s1/2) # `/` or `tensor.div` divides all the elements in the tensor by the  given number



tensor([7, 8])
tensor([14, 15])
tensor([0, 1])
tensor([14, 16])
tensor([3.5000, 4.0000])


# Matrix multiplication:
### It is of two types :
- tensor by numbers which we discussed above,
- element-wise, 
- another is matrix-multiplication (dot product) 

In [7]:
# element-wise multiplication
e1=torch.tensor([5,5,6,9])
e2=torch.tensor([2,2,8,8])

#now if we write e1*e2, we get each element multiplied to its corresponding element from the other tensor
print(e1*e2)

tensor([10, 10, 48, 72])


In [9]:
# matrix-multiplication (using same e1 and e2 tensors from above)

print(e1 @ e2) # `@` or `tensor.matmul()` or `torch.mm()` how come? -> 5*5+5*5+6*8+9*8

tensor(140)


In [12]:
# transpose function (using same e1 and e2 tensors from above)
t1=torch.rand(3,2)
t2=torch.rand(3,2)

tt=t1.T # `tensor.T` to transpose a tensor
print(t1,tt)

tensor([[0.0150, 0.9194],
        [0.6353, 0.4906],
        [0.7971, 0.6467]]) tensor([[0.0150, 0.6353, 0.7971],
        [0.9194, 0.4906, 0.6467]])
