# Reshaping, stacking, squeezing and unsqueezing, and indexing tensors

- reashape : to reshape a tensor to a different shape
- view : returns the view of an tensor but keep the memory same as original tensor
- stacking : combining multiple tensors on top of each other (vstack) or side by side (hstack)
- squeeze : remove all (1) dimensions from a tensor
- unsqueeze : add (1) dimensions from a tensor
- permute : return the view of a tensor with dimensions permuted(swapped) in a certain way
- use indexes to find any element from n-dimensional array


In [2]:
# importing
try:
    import torch
    import numpy
    import matplotlib.pyplot as plt
    print("Done Successfully")
except Exception as e:
    print("Failed to import",e)


Done Successfully


In [3]:
# Reshape
t1= torch.rand([3,4])

#now we can reshape this tensor in all the ways the multiple of rows and columns remains constant  
reshape1=t1.reshape([4,3])
reshape2=t1.reshape([2,2,3])
print(t1)
print(reshape1)
print(reshape2)


tensor([[0.8004, 0.2613, 0.8922, 0.4527],
        [0.9110, 0.6610, 0.0518, 0.9074],
        [0.8437, 0.5873, 0.2867, 0.6249]])
tensor([[0.8004, 0.2613, 0.8922],
        [0.4527, 0.9110, 0.6610],
        [0.0518, 0.9074, 0.8437],
        [0.5873, 0.2867, 0.6249]])
tensor([[[0.8004, 0.2613, 0.8922],
         [0.4527, 0.9110, 0.6610]],

        [[0.0518, 0.9074, 0.8437],
         [0.5873, 0.2867, 0.6249]]])


In [7]:
# view: same concept as in pthon, used to create a copy sharing the same memory location, change its value and you change the original too

ts=torch.arange(1,11)

tv=ts.view(10) #input shape to view in 
tv1=ts.view(5,2)


print("original tensor:",ts)
print("viewing in original shape:",tv)
print("viewing in changed shape:",tv1)


# now change the values of tv/tv1 and see what happens to ts
tv[0]=20
print("value of tv",tv)
print("notice the changed original value ts",ts)
print("also tv1:",tv1) # notice changed value of another derived tensor too

tv=torch.arange(1,6) # I did a great mistake here -tv points to a new tensor, ts is untouched and the old view relationship is gone.
print("this is ts:",ts) 
print("this is tv", tv) #notice unchanged value of ts 

original tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
viewing in original shape: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
viewing in changed shape: tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
value of tv tensor([20,  2,  3,  4,  5,  6,  7,  8,  9, 10])
notice the changed original value ts tensor([20,  2,  3,  4,  5,  6,  7,  8,  9, 10])
also tv1: tensor([[20,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])
this is ts: tensor([20,  2,  3,  4,  5,  6,  7,  8,  9, 10])
this is tv tensor([1, 2, 3, 4, 5])


In [ ]:
# stacking
t=torch.tensor([1,2,3])
t2=torch.tensor([4,5,6])
print(t)

x=torch.stack([t,t2],dim=0)
print(x)


In [ ]:
# Squeezing : remove one fake dimension

x=torch.rand([1,4,1])
print(x)

y=x.squeeze() #removes all 1 dims
print(y)

y1=x.squeeze(0) #removes 1 dim at 0th index 
print(y1)

y2=x.squeeze(2) #removes 1 dim at 2nd index 
print(y2)

y3=x.squeeze(1) #see there is no 1 dim at 1st index, so it does nothing
print(y3)


print(x.size(), y1.size(), y2.size(), y3.size()) #remains same size as of original



In [ ]:
# Unsqueezing : adds a fake dimension, make sure unsqueeze(n) always has an argument
x=torch.rand([2,3])
print(x)

x1=x.unsqueeze(0) # add one dim at 0th index 
print(x1)

x2=x.unsqueeze(1) # add one dim at 1st index
print(x2)

x3=x.unsqueeze(2) # add one dim at 2nd index
print(x3)

print(x.size(), x1.size(), x2.size(), x3.size())

In [ ]:
# Permute
test= torch.rand(size=(144,144,3))
ptest=test.permute(0,2,1)

print(test.size())
print(ptest.size()) # the 0tth and 2nd indexes are swapped 

test=torch.rand(size=(1,2,2))
ptest=test.permute(0,2,1) #swapping 2nd and 1st index

print(test.size())
print(ptest.size()) # the indexes are swapped 

# comparing the data:
print(test)
print(ptest)

In [30]:
# 2D- indexing 
x =torch.arange(1,10).reshape([3,3])
print(x)

print("first row",x[0]) # find first row
print("second row",x[1]) # find second row

print("first column",x[:,0]) # print first column


print("first element:",x[0,0])

print("r1 c3",x[0,2])
print("r2 c2",x[1,1])

# 3D- indexing
y=torch.stack([x,x]) #stacking x above x to get a 3d- tensor
print(y) #see our tensor
print("dimension of y:",y.dim()) #check the dim to confirm 3-d conversion
print("shape of y:",y.shape) # check shape to know your boundaries

print("element at 0th index in y",y[0]) #prints tensor x 
print("element in [1,1,1]",y[1,1,1])


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
first row tensor([1, 2, 3])
second row tensor([4, 5, 6])
first column tensor([1, 4, 7])
first element: tensor(1)
r1 c3 tensor(3)
r2 c2 tensor(5)
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dimension of y: 3
shape of y: torch.Size([2, 3, 3])
element at 0th index in y tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
element in [1,1,1] tensor(5)
