# Numpy and Pytorch Tensors
- numpy is the popular mathemtical computation library for python, thus pytorch has compacity to interact with it.
- data in numpy to ptorch tensor.
- numpy -> tensor -> torch.from_numpy()
- pytorch tensor -> numpy -> tensor.numpy()


In [22]:
# importing
try:
    import torch
    import numpy
    import matplotlib.pyplot as plt
    print("Done Successfully")
except Exception as e:
    print("Failed to import",e)


Done Successfully


In [23]:
# numpy -> tensor
arr=numpy.arange(1.0,11.0) # create an array in numpy :
tensor=torch.from_numpy(arr)
arr,tensor #notice the default dtype of the array is float64 unless specified

tensor_f32=tensor.type(torch.float32)
print(tensor_f32)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [29]:
# experimenting
arr+=1
print(arr,"\n",tensor) #notice how both change; meaning a shared memory

# if we do arr= arr-1
arr= arr-1
print(arr,"\n",tensor) # notice how the array changes but tensor remains same .. thats the major difference in a+=n and a=a+n


[ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.] 
 tensor([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.], dtype=torch.float64)
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.] 
 tensor([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.], dtype=torch.float64)


In [55]:
# tensor -> numpy
tensor= torch.zeros(7)
print(tensor) # notice default dtype float32

# convert this into numpy array :
arr=tensor.numpy()
arr # same data type as tensor 

tensor([0., 0., 0., 0., 0., 0., 0.])


array([0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [56]:
# experimeting 
tensor+=1 # updation follows the shared memory rule 
print(tensor,arr)

tensor=tensor-1 # redeclaration breaks the shared meemory rule 
print(tensor,arr)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]
tensor([0., 0., 0., 0., 0., 0., 0.]) [1. 1. 1. 1. 1. 1. 1.]
