In [1]:
# importing
try:
    import torch
    import numpy
    import matplotlib.pyplot as plt
    print("Done Successfully")
except Exception as e:
    print("Failed to import",e)


Done Successfully


# getting a free gpu:
- gcolab/kaggle.
- use your own.
- use cloud computing : aws, cp, azure etc allow to rent gpu's on cloud and access them.


In [2]:
!nvidia-smi #check gpu 

Tue Jan  6 10:07:30 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.172.08             Driver Version: 570.172.08     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# check for gpu access with pytorch:
torch.cuda.is_available()

True

In [4]:
# set up device agnostic code : use gpu if available, else default to cpu
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
#count the number of devices- when using multiple gpus 
torch.cuda.device_count()


2

In [12]:
# putting tensors on gpu:
tensor=torch.tensor([1,2,3], device='cpu')
print(tensor,"is on",tensor.device )

#move tensor to gpu if availabe:
gtensor=tensor.to(device)
print(gtensor,"is on",gtensor.device )

tensor([1, 2, 3]) is on cpu
tensor([1, 2, 3], device='cuda:0') is on cuda:0


In [15]:
# certain libraries work only on cpu such as numPy
gtensor.numpy() #see this throws an error asking to put the tensor into cpu before using numpy with it 

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [20]:
# so putting a tensor back to cpu and using numpy with it :
ctensor=gtensor.cpu().numpy()
ctensor #converted to numpy array 

array([1, 2, 3])